org.gradle.jvmargs=-Xmx2048m -Djava.net.preferIPv4Stack=true -Dsun.net.spi.nameservice.provider.1=dns,sun
org.gradle.daemon=true
org.gradle.parallel=false
systemProp.http.socketTimeout=60000
systemProp.http.connectionTimeout=60000
systemProp.networkaddress.cache.ttl=0
android.useAndroidX=true
android.enableJetifier=true
